version: 0.0
os: linux
files:
  - source: /LibraryWebApp
    destination: /var/www/LibraryWebApp
hooks:
  ApplicationStop:
    - location: scripts/stop_server
  BeforeInstall:
    - location: scripts/install_dependencies
  AfterInstall:
    - location: scripts/start_server