version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot\LibraryWebApp
hooks:
  ApplicationStop:
    - location: scripts/stop_server.bat
      timeout: 300
  Install:
    - location: scripts/before_install.bat
      timeout: 300
    - location: scripts/create_service.bat
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.bat
      timeout: 300